# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{earnings_estimates}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt White"]
  s.date = %q{2010-04-22}
  s.description = %q{Retrieves and analyzes earnings estimates for a given security.}
  s.email = %q{mattw922@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/classes/Array.html",
     "doc/classes/Array.src/M000001.html",
     "doc/classes/Array.src/M000002.html",
     "doc/classes/EarningsEstimates.html",
     "doc/classes/EarningsEstimates.src/M000003.html",
     "doc/classes/EarningsEstimates.src/M000004.html",
     "doc/classes/EarningsEstimates.src/M000005.html",
     "doc/created.rid",
     "doc/files/lib/array_extensions_rb.html",
     "doc/files/lib/earnings_estimates_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "earnings_estimates.gemspec",
     "lib/array_extensions.rb",
     "lib/earnings_estimates.rb",
     "test/helper.rb",
     "test/test_earnings_estimates.rb"
  ]
  s.homepage = %q{http://github.com/whitethunder/earnings_estimates}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Analyst security earnings estimates analyzer.}
  s.test_files = [
    "test/test_earnings_estimates.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

